# -*- coding: utf-8 -*-
"""Exercicio 04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XgFseBVvpijr8RXjdr2UnXY05jQ9MnMJ
"""

class Atleta():
    def __init__(self,peso):
        self.aposentado = False
        self.aquecendo = False
        self.peso = peso

    def aposentar(self):
        if self.aposentado:
            print("O atleta já está aposentado")
        else:
            print("O atleta entrou na aposentadoria")
            self.aposentado = True

    def sairAposentadoria(self):
        if self.aposentado:
            print("Atleta saiu da aposentadoria")
            self.aposentado = False
        else:
            print("Atleta não está aposentado")

    def aquecer(self):
        if self.aquecendo:
            print("Atleta já aqueceu")
        else:
            print("O atleta está aquecendo")
            self.aquecendo = True


class Corredor(Atleta):
    def __init__(self, peso):
        super().__init__(peso)
        self.correndo = False

    def correr(self):
        if not self.aquecendo:
            print("Corredor não pode correr, ele não aqueceu ainda")
        elif self.aposentado:
            print("Corredor está aposentado, ele não pode correr")
        elif self.correndo:
            print("Corredor já está correndo")
        else:
            print("Corredor começou a correr")
            self.correndo = True

    def pararCorrer(self):
        if not self.correndo:
            print("Corredor não está correndo")
        else:
            print("Corredor parou de correr")
            self.correndo = False

class Nadador(Atleta):
    def __init__(self,peso):
        super().__init__(peso)
        self.nadando = False

    def nadar(self):
        if not self.aquecendo:
            print("Nadador não pode nadar, ele não aqueceu ainda")
        elif self.aposentado:
            print("Nadador está aposentado, ele não pode nadar")
        elif self.nadando:
            print("Nadador já está nadando")
        else:
            print("Nadador começou a nadar")
            self.nadando = True

    def pararNadar(self):
        if not self.nadando:
            print("Nadador não está nadando")
        else:
            print("Nadador parou de nadar")
            self.nadando = False

class Ciclista(Atleta):
    def __init__(self,peso):
        super().__init__(peso)
        self.pedalando= False

    def pedalar(self):
        if not self.aquecendo:
            print("Ciclista não pode pedalar, ele não aqueceu ainda")
        elif self.aposentado:
            print("Ciclista está aposentado, ele não pode pedalar")
        elif self.pedalando:
            print("Ciclista já está pedalando")
        else:
            print("Ciclista começou a pedalar")
            self.pedalando = True

    def pararPedalar(self):
        if not self.pedalando:
            print("Atleta não está pedalando")
        else:
            print("Atleta parou de pedalar")
            self.pedalando = False

class TriAtleta(Corredor, Nadador, Ciclista):
    def __init__(self,peso):
        super().__init__(peso)

    def correr(self):
        if not self.aquecendo:
            print("TriAtleta não pode correr, ele não aqueceu ainda")
        elif self.aposentado:
            print("TriAtleta está aposentado, ele não pode correr")
        elif self.nadando:
            print("TriAtleta não pode correr, pois está nadando")
        elif self.pedalando:
            print("TriAtleta não pode nadar, pois está pedalando")
        elif self.correndo:
            print("TriAtleta já está correndo")
        else:
            print("TriAtleta começou a correr")
            self.correndo = True

    def pararCorrer(self):
        if not self.correndo:
            print("TriAtleta não está correndo")
        else:
            print("TriAtleta parou de correr")
            self.correndo = False

    def nadar(self):
        if not self.aquecendo:
            print("TriAtleta não pode nadar, ele não aqueceu ainda")
        elif self.aposentado:
            print("TriAtleta está aposentado, ele não pode nadar")
        elif self.correndo:
            print("TriAtleta não pode nadar, pois está correndo")
        elif self.pedalando:
            print("TriAtleta não pode nadar, pois está pedalando")
        elif self.nadando:
            print("TriAtleta já está nadando")
        else:
            print("TriAtleta começou a nadar")
            self.nadando = True

    def pararNadar(self):
        if not self.nadando:
            print("TriAtleta não está nadando")
        else:
            print("TriAtleta parou de nadar")
            self.nadando = False

    def pedalar(self):
        if not self.aquecendo:
            print("TriAtleta não pode pedalar, ele não aqueceu ainda")
        elif self.aposentado:
            print("TriAtleta está aposentado, ele não pode pedalar")
        elif self.nadando:
            print("TriAtleta não pode pedalar, pois está nadando")
        elif self.correndo:
            print("TriAtleta não pode pedalar, pois está correndo")
        elif self.pedalando:
            print("TriAtleta já está pedalando")
        else:
            print("TriAtleta começou a pedalar")
            self.pedalando = True

    def pararPedalar(self):
        if not self.pedalando:
            print("TriAtleta não está pedalando")
        else:
            print("TriAtleta parou de pedalar")
            self.pedalando = False

def teste():
    print("Teste Atleta:")
    atleta = Atleta(75)
    atleta.aquecer()
    atleta.aposentar()
    atleta.sairAposentadoria()
    print("\nTeste Corredor:")
    corredor = Corredor(70)
    corredor.aquecer()
    corredor.correr()
    corredor.pararCorrer()
    print("\nTeste Nadador:")
    nadador = Nadador(80)
    nadador.aquecer()
    nadador.nadar()
    nadador.pararNadar()
    print("\nTeste Ciclista:")
    ciclista = Ciclista(65)
    ciclista.aquecer()
    ciclista.pedalar()
    ciclista.pararPedalar()
    print("\nTeste TriAtleta:")
    tri_atleta = TriAtleta(90)
    tri_atleta.aquecer()
    tri_atleta.correr()
    tri_atleta.pararCorrer()
    tri_atleta.nadar()
    tri_atleta.pararNadar()
    tri_atleta.pedalar()
    tri_atleta.pararPedalar()

teste()