pessoa = Pessoa("Pou", 10, 2)
pessoa.comer("maçã")
pessoa.comer("Melão")
pessoa.dormir()
pessoa.falar()
pessoa.pararDeComer()
pessoa.pararDeComer()
pessoa.dormir()
pessoa.dormir()
pessoa.falar()
pessoa.comer("Biscoito")
pessoa.pararDeDormir()
pessoa.pararDeDormir()
pessoa.falar()
pessoa.dormir()
pessoa.comer("Milho")
pessoa.pararDeFalar()
pessoa.pararDeFalar()
