pessoa = Pessoa("Pou", 10, 2)
pessoa.comer("maçã")
pessoa.comer("Melão")
pessoa.dormir()
pessoa.falar()
pessoa.pararDeComer()
pessoa.pararDeComer()
pessoa.dormir()
pessoa.dormir()
pessoa.falar()
pessoa.comer("Biscoito")
pessoa.pararDeDormir()
pessoa.pararDeDormir()
pessoa.falar()
pessoa.dormir()
pessoa.comer("Milho")
pessoa.pararDeFalar()
pessoa.pararDeFalar()

from Classe import ContaBancaria
p = ContaBancaria(1234, "José","Caixa")
p.ativarConta()
p.depositar(100)
p.ativarConta()
p.depositar(200)
p.verificarSaldo()
p.sacar(200)
p.sacar(150)
p.sacar(0)
p.verificarSaldo()
p.desativarConta()
p.sacar(100)
p.desativarConta()
p.depositar(10)
