# -*- coding: utf-8 -*-
"""API Cep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Z_KtgeXdxdFMR_c_ip3ys7qzcPQ_Pbm
"""

import requests

resposta = "sim"

while resposta == "sim" or resposta == "Sim":
    print("Verifique seu Endereço Aqui.")
    cep = str(input("Digite o CEP: "))

    if len(cep) != 8:
        print("CEP Inválido!")
        exit()
    consulta = requests.get(f"https://viacep.com.br/ws/{cep}/json/")
    print(consulta.json())
    resposta = input("Deseja inserir outro CEP: [Sim ou Não]")